/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 public/models/monitor.gltf -K -k 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/monitor.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="RootNode">
          <group name="OfficeChair" position={[-0.229, 0.039, -0.554]} rotation={[-Math.PI / 2, 0, 2.786]}>
            <mesh name="OfficeChair_1" geometry={nodes.OfficeChair_1.geometry} material={textureMaterial} />
            <mesh name="OfficeChair_2" geometry={nodes.OfficeChair_2.geometry} material={textureMaterial} />
            <mesh name="OfficeChair_3" geometry={nodes.OfficeChair_3.geometry} material={textureMaterial} />
          </group>
        </group>
        <group name="monitor" position={[0.595, 1.695, -2.044]} rotation={[0, -0.25, 0]}>
          <mesh name="Monitor1" geometry={nodes.Monitor1.geometry} material={textureMaterial} />
        </group>
        <group name="Empty" position={[-0.079, 0.729, -0.889]} rotation={[-Math.PI, 0.313, -Math.PI]}>
          <group name="Armature">
            <primitive object={nodes.Hips} />
            <skinnedMesh name="Wolf3D_Body" geometry={nodes.Wolf3D_Body.geometry} material={textureMaterial} />
            <skinnedMesh name="Wolf3D_Glasses" geometry={nodes.Wolf3D_Glasses.geometry} material={textureMaterial} />
            <skinnedMesh name="Wolf3D_Hair" geometry={nodes.Wolf3D_Hair.geometry} material={textureMaterial} />
            <skinnedMesh name="Wolf3D_Outfit_Bottom" geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={textureMaterial} />
            <skinnedMesh name="Wolf3D_Outfit_Footwear" geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={textureMaterial} />
            <skinnedMesh name="Wolf3D_Outfit_Top" geometry={nodes.Wolf3D_Outfit_Top.geometry} material={textureMaterial} />
            <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={textureMaterial} />
            <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={textureMaterial} />
            <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={textureMaterial} />
            <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={textureMaterial} />
          </group>
        </group>
        <mesh name="CoconutPalmTree_mesh" geometry={nodes.CoconutPalmTree_mesh.geometry} material={textureMaterial} />
        <group name="plant" position={[-2.124, 0.535, -2.116]}>
          <mesh name="mesh31856083" geometry={nodes.mesh31856083.geometry} material={textureMaterial} />
          <mesh name="mesh31856083_1" geometry={nodes.mesh31856083_1.geometry} material={textureMaterial} />
          <mesh name="mesh31856083_2" geometry={nodes.mesh31856083_2.geometry} material={textureMaterial} />
        </group>
        <group name="pokeman" position={[-0.085, 3.175, -2.479]} rotation={[-Math.PI, 0.063, -Math.PI]}>
          <mesh name="mesh434900071" geometry={nodes.mesh434900071.geometry} material={textureMaterial} />
          <mesh name="mesh434900071_1" geometry={nodes.mesh434900071_1.geometry} material={textureMaterial} />
          <mesh name="mesh434900071_2" geometry={nodes.mesh434900071_2.geometry} material={textureMaterial} />
          <mesh name="mesh434900071_3" geometry={nodes.mesh434900071_3.geometry} material={textureMaterial} />
          <mesh name="mesh434900071_4" geometry={nodes.mesh434900071_4.geometry} material={textureMaterial} />
          <mesh name="mesh434900071_5" geometry={nodes.mesh434900071_5.geometry} material={textureMaterial} />
        </group>
        <group name="SM_ShelfSM_Shelf1" position={[-0.632, 2.654, -2.633]}>
          <mesh name="SM_ShelfSM_Shelf1_1" geometry={nodes.SM_ShelfSM_Shelf1_1.geometry} material={textureMaterial} />
          <mesh name="SM_ShelfSM_Shelf1_1_1" geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry} material={textureMaterial} />
        </group>
        <group name="Node" position={[-1.304, 3.128, -2.578]}>
          <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={textureMaterial} />
          <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={textureMaterial} />
          <mesh name="Node-Mesh_2" geometry={nodes['Node-Mesh_2'].geometry} material={textureMaterial} />
        </group>
        <group name="keyboard" position={[0.185, 1.522, -1.555]} rotation={[0, -0.249, 0]}>
          <mesh name="mesh34220672" geometry={nodes.mesh34220672.geometry} material={textureMaterial} />
          <mesh name="mesh34220672_1" geometry={nodes.mesh34220672_1.geometry} material={textureMaterial} />
          <mesh name="mesh34220672_2" geometry={nodes.mesh34220672_2.geometry} material={textureMaterial} />
          <mesh name="mesh34220672_3" geometry={nodes.mesh34220672_3.geometry} material={textureMaterial} />
        </group>
        <mesh name="Comp_Mouse" geometry={nodes.Comp_Mouse.geometry} material={textureMaterial} />
        <group name="rugRounded" position={[1.276, 0.017, -1.281]} rotation={[0, 0.034, 0]}>
          <mesh name="rugRounded_2" geometry={nodes.rugRounded_2.geometry} material={textureMaterial} />
          <mesh name="rugRounded_2_1" geometry={nodes.rugRounded_2_1.geometry} material={textureMaterial} />
        </group>
        <group name="desk" position={[0, 0, -1.835]} rotation={[1.573, -0.011, 1.565]}>
          <mesh name="Plane001_Plane002" geometry={nodes.Plane001_Plane002.geometry} material={textureMaterial} />
          <mesh name="Plane001_Plane002_1" geometry={nodes.Plane001_Plane002_1.geometry} material={textureMaterial} />
          <mesh name="Plane001_Plane002_2" geometry={nodes.Plane001_Plane002_2.geometry} material={textureMaterial} />
          <mesh name="Plane001_Plane002_3" geometry={nodes.Plane001_Plane002_3.geometry} material={textureMaterial} />
          <mesh name="Plane001_Plane002_4" geometry={nodes.Plane001_Plane002_4.geometry} material={textureMaterial} />
        </group>
        <mesh name="Screen" geometry={nodes.Screen.geometry} material={textureMaterial} />
        <group name="Plane">
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={textureMaterial} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={textureMaterial} />
          <mesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={textureMaterial} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/monitor.gltf')
