/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 public/models/scene.gltf -K -k 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="RootNode">
          <group name="OfficeChair" position={[-0.229, 0.039, -0.554]} rotation={[-Math.PI / 2, 0, 2.786]}>
            <mesh name="OfficeChair_1" geometry={nodes.OfficeChair_1.geometry} material={materials.Grey} />
            <mesh name="OfficeChair_2" geometry={nodes.OfficeChair_2.geometry} material={materials.Black} />
            <mesh name="OfficeChair_3" geometry={nodes.OfficeChair_3.geometry} material={materials.Chair} />
          </group>
        </group>
        <group name="monitor" position={[0.595, 1.695, -2.044]} rotation={[0, -0.25, 0]}>
          <group name="Monitor1" position={[-0.147, -0.082, -0.108]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Monitor1_1" geometry={nodes.Monitor1_1.geometry} material={materials.Plastic1Monitor1} />
            <mesh name="Monitor1_2" geometry={nodes.Monitor1_2.geometry} material={materials.Screen1Monitor1} />
          </group>
        </group>
        <group name="Empty" position={[-0.178, 0.286, 0.474]} rotation={[0, -0.835, 0]} scale={1.643}>
          <group name="Armature" position={[-0.4, -0.069, -0.403]} rotation={[Math.PI, -0.471, Math.PI]}>
            <primitive object={nodes.Hips} />
            <skinnedMesh name="Wolf3D_Body" geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
            <skinnedMesh name="Wolf3D_Glasses" geometry={nodes.Wolf3D_Glasses.geometry} material={materials.Wolf3D_Glasses} skeleton={nodes.Wolf3D_Glasses.skeleton} />
            <skinnedMesh name="Wolf3D_Hair" geometry={nodes.Wolf3D_Hair.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Wolf3D_Hair.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Bottom" geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Footwear" geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Top" geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
            <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} />
            <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} />
            <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} />
            <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} />
          </group>
        </group>
        <mesh name="CoconutPalmTree_mesh" geometry={nodes.CoconutPalmTree_mesh.geometry} material={materials.CoconutPalmTree_mat} position={[1.814, -0.031, -1.786]} />
        <group name="plant" position={[-2.124, 0.535, -2.116]}>
          <mesh name="mesh31856083" geometry={nodes.mesh31856083.geometry} material={materials.mat9} />
          <mesh name="mesh31856083_1" geometry={nodes.mesh31856083_1.geometry} material={materials.mat21} />
          <mesh name="mesh31856083_2" geometry={nodes.mesh31856083_2.geometry} material={materials.mat20} />
        </group>
        <group name="pokeman" position={[-0.085, 3.175, -2.479]} rotation={[-Math.PI, 0.063, -Math.PI]}>
          <mesh name="mesh434900071" geometry={nodes.mesh434900071.geometry} material={materials.mat14} />
          <mesh name="mesh434900071_1" geometry={nodes.mesh434900071_1.geometry} material={materials.mat13} />
          <mesh name="mesh434900071_2" geometry={nodes.mesh434900071_2.geometry} material={materials.mat12} />
          <mesh name="mesh434900071_3" geometry={nodes.mesh434900071_3.geometry} material={materials['mat21.001']} />
          <mesh name="mesh434900071_4" geometry={nodes.mesh434900071_4.geometry} material={materials.mat23} />
          <mesh name="mesh434900071_5" geometry={nodes.mesh434900071_5.geometry} material={materials.mat11} />
        </group>
        <group name="SM_ShelfSM_Shelf1" position={[-0.632, 2.654, -2.633]}>
          <mesh name="SM_ShelfSM_Shelf1_1" geometry={nodes.SM_ShelfSM_Shelf1_1.geometry} material={materials.lambert2SG} />
          <mesh name="SM_ShelfSM_Shelf1_1_1" geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry} material={materials.lambert3SG} />
        </group>
        <group name="Node" position={[-1.304, 3.128, -2.578]}>
          <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={materials.lambert4SG} />
          <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={materials['lambert2SG.001']} />
          <mesh name="Node-Mesh_2" geometry={nodes['Node-Mesh_2'].geometry} material={materials['lambert3SG.001']} />
        </group>
        <group name="keyboard" position={[-0.028, 1.364, -1.519]} rotation={[0, -0.211, 0]}>
          <mesh name="mesh34220672" geometry={nodes.mesh34220672.geometry} material={materials['mat21.002']} />
          <mesh name="mesh34220672_1" geometry={nodes.mesh34220672_1.geometry} material={materials.mat22} />
          <mesh name="mesh34220672_2" geometry={nodes.mesh34220672_2.geometry} material={materials.mat16} />
          <mesh name="mesh34220672_3" geometry={nodes.mesh34220672_3.geometry} material={materials['mat9.001']} />
        </group>
        <mesh name="Comp_Mouse" geometry={nodes.Comp_Mouse.geometry} material={materials['lambert3SG.002']} position={[0.589, 1.323, -1.334]} rotation={[-Math.PI, 0.264, -Math.PI]} />
        <group name="rugRounded" position={[1.276, 0.017, -1.281]} rotation={[0, 0.034, 0]}>
          <mesh name="rugRounded_2" geometry={nodes.rugRounded_2.geometry} material={materials.carpetDarker} />
          <mesh name="rugRounded_2_1" geometry={nodes.rugRounded_2_1.geometry} material={materials.carpet} />
        </group>
        <group name="desk" position={[0, 0, -1.835]} rotation={[1.573, -0.011, 1.565]}>
          <mesh name="Plane001_Plane002" geometry={nodes.Plane001_Plane002.geometry} material={materials.BlackWood} />
          <mesh name="Plane001_Plane002_1" geometry={nodes.Plane001_Plane002_1.geometry} material={materials.BlackCoatSteel} />
          <mesh name="Plane001_Plane002_2" geometry={nodes.Plane001_Plane002_2.geometry} material={materials.GrayPlastic} />
          <mesh name="Plane001_Plane002_3" geometry={nodes.Plane001_Plane002_3.geometry} material={materials.WhiteSteelScrew} />
          <mesh name="Plane001_Plane002_4" geometry={nodes.Plane001_Plane002_4.geometry} material={materials.BlackPlastic} />
        </group>
        <group name="Plane">
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.floor} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials['wall.001']} />
          <mesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={materials['default']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
